import {clean,database,digest,fail,passwordHash,ROLES,seed,viewer} from '@/lib/board-server';
export const dynamic='force-dynamic';
export async function GET(request:Request){try{const me=await viewer(request);if(!me)return fail('Please sign in.',401);await seed();const db=database();const result=await db.batch(['categories','channels','cards','task_groups','tasks','comments'].map(n=>db.prepare('SELECT * FROM '+n+' ORDER BY rowid')));const members=await db.prepare('SELECT id,username,about,avatar,scale,roles FROM users ORDER BY username').all();return Response.json({me,members:members.results,categories:result[0].results,channels:result[1].results,cards:result[2].results,groups:result[3].results,tasks:result[4].results,comments:result[5].results},{headers:{'Cache-Control':'no-store'}});}catch(e){console.error(e);return fail('Could not load the board. Please try again.',503);}}
export async function POST(request:Request){try{
if(request.headers.get('origin')!==new URL(request.url).origin)return fail('Invalid request.',403);
if(Number(request.headers.get('content-length')||0)>16000)return fail('Request too large.',413);
const raw=await request.text();if(raw.length>16000)return fail('Request too large.',413);const p=JSON.parse(raw);const db=database();
if(p.action==='signup'||p.action==='login'){
const username=clean(p.username,32).toLowerCase();const password=typeof p.password==='string'?p.password:'';
if(!/^[a-z0-9_]{3,24}$/.test(username)||password.length<8||password.length>128)return fail('Use 3–24 letters, numbers or underscores for your username, and 8–128 characters for your password.');
const key=await digest(request.headers.get('cf-connecting-ip')||'local');const now=Date.now();
await db.prepare('INSERT INTO limits (key,count,expires) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN expires<? THEN 1 ELSE count+1 END, expires=CASE WHEN expires<? THEN ? ELSE expires END').bind(key,now+900000,now,now,now+900000).run();
const limit=await db.prepare('SELECT count FROM limits WHERE key=?').bind(key).first<{count:number}>();if(limit&&limit.count>20)return fail('Too many attempts. Try again in 15 minutes.',429);
let user=await db.prepare('SELECT * FROM users WHERE username=?').bind(username).first<any>();
if(p.action==='signup'){if(user)return fail('This username is taken.',409);const salt=crypto.randomUUID();user={id:crypto.randomUUID(),username};try{await db.prepare('INSERT INTO users (id,username,password,salt) VALUES (?,?,?,?)').bind(user.id,username,await passwordHash(password,salt),salt).run();}catch{return fail('This username is taken.',409);}}
else {const computed=await passwordHash(password,user?.salt||'missing-user-salt');if(!user||computed!==user.password)return fail('Incorrect username or password.',401);}
const token=crypto.randomUUID()+crypto.randomUUID();await db.prepare('INSERT INTO sessions (token,user_id,expires) VALUES (?,?,?)').bind(await digest(token),user.id,now+604800000).run();
return Response.json({ok:true},{headers:{'Set-Cookie':`sf_session=${token}; Path=/; HttpOnly; SameSite=Lax; Max-Age=604800${new URL(request.url).protocol==='https:'?'; Secure':''}`}});
}
const me=await viewer(request);if(!me)return fail('Please sign in.',401);
if(p.action==='logout'){const token=request.headers.get('cookie')?.match(/(?:^|;\s*)sf_session=([^;]+)/)?.[1];if(token)await db.prepare('DELETE FROM sessions WHERE token=?').bind(await digest(token)).run();return Response.json({ok:true},{headers:{'Set-Cookie':'sf_session=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0'}});}
if(p.action==='profile'){const roles=Array.isArray(p.roles)?p.roles.filter((x:unknown)=>typeof x==='string'&&ROLES.includes(x)):[];const avatar=clean(p.avatar,200);if(avatar&&!(await db.prepare('SELECT id FROM uploads WHERE id=? AND user_id=?').bind(avatar.replace('/api/image/',''),me.id).first()))return fail('Invalid photo.');await db.prepare('UPDATE users SET about=?,avatar=?,scale=?,roles=? WHERE id=?').bind(clean(p.about,1000),avatar,Math.max(100,Math.min(300,Number(p.scale)||100)),JSON.stringify([...new Set(roles)]),me.id).run();}
else if(p.action==='category'){const n=clean(p.name);if(!n)return fail('Category name is required.');await db.prepare('INSERT INTO categories (id,name) VALUES (?,?)').bind(crypto.randomUUID(),n).run();}
else if(p.action==='channel'){const n=clean(p.name);if(!n)return fail('Channel name is required.');await db.prepare('INSERT INTO channels (id,category_id,name) VALUES (?,?,?)').bind(crypto.randomUUID(),clean(p.category_id),n).run();}
else if(p.action==='card'){const n=clean(p.name);if(!n)return fail('Card name is required.');const image=clean(p.image,200);if(image&&!(await db.prepare('SELECT id FROM uploads WHERE id=?').bind(image.replace('/api/image/','')).first()))return fail('Invalid image.');const tags=JSON.stringify(clean(p.tags,250).split(',').map((s:string)=>s.trim()).filter(Boolean).slice(0,8));if(p.id){await db.prepare('UPDATE cards SET name=?,description=?,image=?,tags=? WHERE id=?').bind(n,clean(p.description,2000),image,tags,clean(p.id)).run();}else{await db.prepare('INSERT INTO cards (id,channel_id,name,description,image,tags) VALUES (?,?,?,?,?,?)').bind(crypto.randomUUID(),clean(p.channel_id),n,clean(p.description,2000),image,tags).run();}}
else if(p.action==='group'){if(!clean(p.name))return fail('Checklist name is required.');const id=crypto.randomUUID();await db.batch([db.prepare('INSERT INTO task_groups (id,card_id,name) VALUES (?,?,?)').bind(id,clean(p.card_id),clean(p.name)),...(p.template?['Animation','SFX','VFX','Backend'].map(n=>db.prepare('INSERT INTO tasks (id,group_id,name) VALUES (?,?,?)').bind(crypto.randomUUID(),id,n)):[])]);}
else if(p.action==='task'){if(!clean(p.name))return fail('Task name is required.');await db.prepare('INSERT INTO tasks (id,group_id,name) VALUES (?,?,?)').bind(crypto.randomUUID(),clean(p.group_id),clean(p.name)).run();}
else if(p.action==='toggle'){await db.prepare('UPDATE tasks SET done=? WHERE id=?').bind(p.done?1:0,clean(p.id)).run();}
else if(p.action==='deadline'){const date=clean(p.deadline,10);if(date&&(!/^\d{4}-\d{2}-\d{2}$/.test(date)||Number.isNaN(Date.parse(date))||new Date(date).toISOString().slice(0,10)!==date))return fail('Choose a valid date.');await db.prepare('UPDATE tasks SET deadline=? WHERE id=?').bind(date,clean(p.id)).run();}
else if(p.action==='assign'){await db.prepare('UPDATE tasks SET assignee=? WHERE id=?').bind(clean(p.assignee)||null,clean(p.id)).run();}
else if(p.action==='comment'){const body=clean(p.body,2000);if(!body)return fail('Comment cannot be empty.');const task=await db.prepare('SELECT id FROM tasks WHERE id=?').bind(clean(p.task_id)).first();if(!task)return fail('Task not found.');await db.prepare('INSERT INTO comments (id,task_id,user_id,body,created_at) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),clean(p.task_id),me.id,body,Date.now()).run();}
else return fail('Invalid action.');return Response.json({ok:true});
}catch(e){console.error(e);return fail('Could not save. Check your input and try again.',500);}}
